# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31090d5c642eb18422eee534c75071a75bbad4c1ee750fb725e3c922d9f4c7164f785b0b55f6837ea37ffc8c1f4786e90d27cd134be9f5ffe72f11225a22350f

test:
  secret_key_base: c1070f5af96c1119f070bf2e2be3f1eedf41231c8a240de33783749556b54172928f1dc107c76d9126d0ea48b0d70121ee1a622de867ce9aed3135c1205bacce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
